### PR TITLE
Update to v0.4

### PR DESCRIPTION
**Pull request by constantinpape**

### CODE REVIEW

**Comment by constantinpape** [comment]
This PR now contains all the changes necessary to transition to v0.4, but is still WIP.
It requires https://github.com/bioimage-io/spec-bioimage-io/pull/307 to be merged and fixing the issue addressed in https://github.com/bioimage-io/spec-bioimage-io/pull/305 (@FynnBe will fix this in a different manner).

**Comment by constantinpape** [comment]
We should also address https://github.com/bioimage-io/core-bioimage-io-python/issues/175 here.

**Comment by FynnBe** [comment]
yay! main passes!

**Comment by FynnBe** [comment]
needs: https://github.com/bioimage-io/spec-bioimage-io/pull/310

**Comment by constantinpape** [comment]
All tests on main pass, so I will merge it.

**Pull request merged**
