### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by FynnBe**

### CODE REVIEW

**Comment by constantinpape** [comment]
Just fyi: you can avoid the onnx related bugs with pytorch 2.0 by adding `onnx` to the env, see my changes in https://github.com/bioimage-io/core-bioimage-io-python/pull/336

**Comment by constantinpape** [comment]
And I am not sure if keeping the `test-spec-rf-legacy` env around is sustainable; if you can't fix it I suggest we get rid of it.

**Comment by FynnBe** [comment]
> Just fyi: you can avoid the onnx related bugs with pytorch 2.0 by adding `onnx` to the env, see my changes in #336

ah, thanks!

**Comment by FynnBe** [comment]
> And I am not sure if keeping the `test-spec-rf-legacy` env around is sustainable; if you can't fix it I suggest we get rid of it.

I hope https://github.com/bioimage-io/core-bioimage-io-python/pull/337/commits/29f4b77511224b039e6007c37bb779cb8e2e3835 has fixed the legacy specific issue...

**Comment by FynnBe** [comment]
hmm.. so, the main issue was the caching. I'll try to get it work properly to speed up testing.

**Comment by constantinpape** [comment]
> hmm.. so, the main issue was the caching. I'll try to get it work properly to speed up testing.

Ok, can we do this in a separate PR though? I think we should release the fix for the grid image as soon as possible, it's currently blocking some other releases for me + it means that `build_model` is not working for users who have a newer PIL / imageio version.

**Comment by FynnBe** [comment]
yes, of course! I'll merge once the tests ran through to make sure the tests really pass now and do the caching separately! 👍

**Pull request merged**
