### PR TITLE
Extend test resources

### PR DESCRIPTION
**Pull request by FynnBe**
`test_resource` and `test_model` now include
- test for availability of all paths or urls (can cause failure)
- test for a '# validation' section in model documentation (always passes, only generates warning)

### CODE REVIEW

**Comment by FynnBe** [comment]
needs https://github.com/bioimage-io/spec-bioimage-io/pull/455

**Review by constantinpape — COMMENTED** [review]
Can you copy&paste examples for how the output of the `test-model` command looks now when it passes or fails.

**Comment by FynnBe** [comment]
previous
```
bioimageio test-model C:\Users\fbeut\Downloads\mu-lux_ctc_phc-c2dl-psc\model.yaml
C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\_resolve_source.py:394: UserWarning: found cached \Users\fbeut\bioimageio_cache\https\raw.githubusercontent.com\bioimage-io\bioimage.io\main\site.config.json. Skipping download of https://raw.githubusercontent.com/bioimage-io/bioimage.io/main/site.config.json.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.")
C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\_resolve_source.py:394: UserWarning: found cached \Users\fbeut\bioimageio_cache\https\bioimage-io.github.io\collection-bioimage-io\collection.json. Skipping download of https://bioimage-io.github.io/collection-bioimage-io/collection.json.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.")
C:\conda\envs\bio-core-tf\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\conda\envs\bio-core-tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
bioimageio.spec 0.4.6post2
implementing:
	collection RDF 0.2.2
	general RDF 0.2.2
	model RDF 0.4.6
bioimageio.core 0.5.3post2
C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\schema.py:46: ValidationWarning: tags: Missing tags for categories: [{'modality': ['electron-microscopy', 'cryo-electron-microscopy', 'fluorescence-light-microscopy', 'transmission-light-microscopy', 'super-resolution-microscopy', 'x-ray-microscopy', 'force-microscopy', 'high-content-imaging', 'whole-slide-imaging', 'other']}, {'dims': ['2d', '3d', '2d-t', '3d-t']}, {'content': ['cells', 'nuclei', 'extracellular-vesicles', 'tissue', 'plant', 'mitochondria', 'vasculature', 'cell-membrane', 'brain', 'whole-organism']}, {'framework': ['tensorflow', 'pytorch', 'tensorflow.js']}, {'network': ['unet', 'densenet', 'resnet', 'inception', 'shufflenet']}, {'task': ['semantic-segmentation', 'instance-segmentation', 'object-detection', 'image-classification', 'denoising', 'image-restoration', 'image-reconstruction', 'in-silico-labeling']}]
  warnings.warn(msg, category=ValidationWarning)
C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\model\v0_3\schema.py:760: UserWarning: missing 'tensorflow_version' entry for weights format keras_hdf5
  warnings.warn(f"missing 'tensorflow_version' entry for weights format {weights_format}")
C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\schema.py:46: ValidationWarning: name: Unrecognized run mode 'deepimagej'
  warnings.warn(msg, category=ValidationWarning)
C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\schema.py:46: ValidationWarning: weights:keras_hdf5: missing 'tensorflow_version'
  warnings.warn(msg, category=ValidationWarning)
C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\_resolve_source.py:394: UserWarning: found cached \Users\fbeut\bioimageio_cache\https\zenodo.org\record\4155785\files\MU-Lux_CTC_unet_PhC-C2DL-PSC.h5. Skipping download of https://zenodo.org/record/4155785/files/MU-Lux_CTC_unet_PhC-C2DL-PSC.h5.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.")
C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\_resolve_source.py:396: UserWarning: Reached cache warnings limit. No more warnings about cache hits will be issued.
  warnings.warn(f"Reached cache warnings limit. No more warnings about cache hits will be issued.")
Model test for C:\Users\fbeut\Downloads\mu-lux_ctc_phc-c2dl-psc\model.yaml using tensorflow_saved_model_bundle weight format has FAILED!
{'bioimageio_core_version': '0.5.3post2',
 'bioimageio_spec_version': '0.4.6post2',
 'error': "Shape (720, 576, 1, 1, 0) of test input 0 'input' does not match "
          'input shape description: ParametrizedInputShape(min=[1, 226, 226, '
          '1], step=[0, 32, 32, 0]).',
 'name': 'reproduced test outputs from test inputs',
 'status': 'failed',
 'traceback': ['  File '
               '"C:\\repos\\bioimage-io\\python-bioimage-io\\bioimageio\\core\\resource_tests.py", '
               'line 134, in test_resource\n'
               '    f"Shape {tuple(ipt.shape)} of test input {idx} '
               '\'{ipt_spec.name}\' does not match "\n']}

Process finished with exit code 1
```

**Comment by constantinpape** [comment]
> previous
> 

What about the new output?

**Comment by FynnBe** [comment]
new:
```
bioimageio test-model C:\Users\fbeut\Downloads\mu-lux_ctc_phc-c2dl-psc\model.yaml
C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\_resolve_source.py:395: CacheWarning: found cached \Users\fbeut\bioimageio_cache\https\raw.githubusercontent.com\bioimage-io\bioimage.io\main\site.config.json. Skipping download of https://raw.githubusercontent.com/bioimage-io/bioimage.io/main/site.config.json.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.", category=CacheWarning)
C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\_resolve_source.py:395: CacheWarning: found cached \Users\fbeut\bioimageio_cache\https\bioimage-io.github.io\collection-bioimage-io\collection.json. Skipping download of https://bioimage-io.github.io/collection-bioimage-io/collection.json.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.", category=CacheWarning)
bioimageio.spec 0.4.6post2
implementing:
	collection RDF 0.2.2
	general RDF 0.2.2
	model RDF 0.4.6
bioimageio.core 0.5.3post2

testing model C:\Users\fbeut\Downloads\mu-lux_ctc_phc-c2dl-psc\model.yaml...
load resource description: passed
has expected resource type: passed
All URLs and paths available: failed
traceback:
  File "C:\repos\bioimage-io\python-bioimage-io\bioimageio\core\resource_tests.py", line 85, in _test_resource_urls
    SourceNodeChecker(root_path=rd.root_path).visit(rd)
  File "C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\node_transformer.py", line 34, in visit
    visitor(node)
  File "C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\node_transformer.py", line 41, in generic_visit
    self.visit(value)
  File "C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\node_transformer.py", line 34, in visit
    visitor(node)
  File "C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\node_transformer.py", line 43, in generic_visit
    [self.visit(subnode) for subnode in node.values()]
  File "C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\node_transformer.py", line 43, in <listcomp>
    [self.visit(subnode) for subnode in node.values()]
  File "C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\node_transformer.py", line 34, in visit
    visitor(node)
  File "C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\node_transformer.py", line 41, in generic_visit
    self.visit(value)
  File "C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\node_transformer.py", line 34, in visit
    visitor(node)
  File "C:\repos\bioimage-io\python-bioimage-io\bioimageio\core\resource_io\utils.py", line 45, in visit_WindowsPath
    self._visit_source(leaf)
  File "C:\repos\bioimage-io\python-bioimage-io\bioimageio\core\resource_io\utils.py", line 35, in _visit_source
    if not source_available(leaf, self.root_path):
  File "C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\_resolve_source.py", line 362, in source_available
    local_path_or_remote_uri = resolve_local_source(source, root_path)
  File "C:\repos\bioimage-io\spec-bioimage-io\bioimageio\spec\shared\_resolve_source.py", line 334, in resolve_local_source
    raise FileNotFoundError(f"Could not find {source}")

error: ('Could not find '       
 'C:\\Users\\fbeut\\Downloads\\mu-lux_ctc_phc-c2dl-psc\\tensorflow_saved_model_bundle.zip')
source_name: 'Pancreatic Cell Phase Contrast Segmentation (DeepWater - CTC submission)'
Test documentation completeness.: passed
reproduce test outputs from test inputs: failed
traceback:
  File "C:\repos\bioimage-io\python-bioimage-io\bioimageio\core\resource_tests.py", line 139, in _test_model_inference
    f"Shape {tuple(ipt.shape)} of test input {idx} '{ipt_spec.name}' does not match "

error: ("Shape (720, 576, 1, 1, 0) of test input 0 'input' does not match input shape "       
 'description: ParametrizedInputShape(min=[1, 226, 226, 1], step=[0, 32, 32, '       
 '0]).')
source_name: 'Pancreatic Cell Phase Contrast Segmentation (DeepWater - CTC submission)'

❌ Model C:\Users\fbeut\Downloads\mu-lux_ctc_phc-c2dl-psc\model.yaml FAILED!

Process finished with exit code 1

```

**Comment by FynnBe** [comment]
@constantinpape any idea how to resolve:

```Looking for: ['black', 'bioimageio.spec', 'conda-build', "h5py[version='>=2.10,<2.11']", 'mypy', 'pip', 'pytest', "python[version='>=3.7,<3.8']", 'xarray', "tensorflow[version='>1.14,<2.0']", "tifffile[version='<=2022.4.8']", 'keras', 'python=3.7']
  
  
  Encountered problems while solving:
    - package tensorflow-1.15.0-mkl_py37h28c19af_0 is excluded by strict repo priority"
   
```
(seems unrelated to this PR)

**Pull request merged**
