### PR TITLE
Add support for tensorflow 2

### LINKED ISSUE #302: Weight conversion for tensorflow 2 is not yet implemented.
I'm trying to  export a TensorFlow 2 model into deepImageJ format but it gives errors as the function seems to not be implemented for it:

```python
from bioimageio.core.weight_converter.keras import convert_weights_to_tensorflow_saved_model_bundle
```
```python
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
1/1 [==============================] - 0s 153ms/step
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-22-95f300b64ebb>](https://localhost:8080/#) in <module>
    197 if os.path.exists(tf_weight_path):
    198   rmtree(tf_weight_path)
--> 199 convert_weights_to_tensorflow_saved_model_bundle(output_path, tf_weight_path + ".zip")
    200 add_weights(output_path, tf_weight_path + ".zip", output_path, tensorflow_version=tf.__version__)
    201 

[/usr/local/lib/python3.7/dist-packages/bioimageio/core/weight_converter/keras/tensorflow.py](https://localhost:8080/#) in convert_weights_to_tensorflow_saved_model_bundle(model_spec, output_path)
    105         return _convert_tf1(weight_path, str(path_), model.inputs[0].name, model.outputs[0].name, zip_weights)
    106     else:
--> 107         raise NotImplementedError("Weight conversion for tensorflow 2 is not yet implemented.")

NotImplementedError: Weight conversion for tensorflow 2 is not yet implemented.
```
An example of the notebook to reproduce this error can be checked here: https://github.com/HenriquesLab/ZeroCostDL4Mic/pull/219

The notebook can also be used with binary images but just in case, data from [here](https://zenodo.org/record/5639253#.Y1vuMuzP06E) can also be used.
@constantinpape

### PR DESCRIPTION
**Pull request by constantinpape**
Fixes #302

### CODE REVIEW

**Comment by constantinpape** [comment]
@FynnBe could you have a look at the failing tests?
I think the problem is that we also need to distinguish between keras models that are compatible with tf1 / tf2. But I don't quite understand the logic in conftest for doing this.

**Comment by esgomezm** [comment]
> @FynnBe could you have a look at the failing tests? I think the problem is that we also need to distinguish between keras models that are compatible with tf1 / tf2. But I don't quite understand the logic in conftest for doing this.

Example of a keras model here: https://github.com/bioimage-io/core-bioimage-io-python/issues/302#issuecomment-1296977109

**Comment by FynnBe** [comment]
errors in [31ff72f](https://github.com/bioimage-io/core-bioimage-io-python/pull/304/commits/31ff72f34fca0c48ac6b71fda95dfed420a16a39) might have been caused by some http error, leading to an emtpy response, throwing a json error... could not reproduce this locally...

**Comment by constantinpape** [comment]
> Example of a keras model here: [#302 (comment)](https://github.com/bioimage-io/core-bioimage-io-python/issues/302#issuecomment-1296977109)

I have added an example model based on https://bioimage.io/#/?tags=bacillus-subtilis&id=10.5281%2Fzenodo.7261974 already @esgomezm.

> errors in [31ff72f](https://github.com/bioimage-io/core-bioimage-io-python/pull/304/commits/31ff72f34fca0c48ac6b71fda95dfed420a16a39) might have been caused by some http error, leading to an emtpy response, throwing a json error... could not reproduce this locally...

Thanks for taking care of the tests @FynnBe.
I can't reproduce the test failures locally either, even after clearing the cache. Not sure why this is going wrong consistently in the tests here. I will run again in a few hours to see if this is temporary.

**Comment by constantinpape** [comment]
I get this test failure locally though:
```
__________________________________________________________________________________ test_assert_dtype __________________________________________________________________________________
                                                                                                                                                                                       
    def test_assert_dtype():                                                                                                                                                           
        from bioimageio.core.prediction_pipeline._processing import AssertDtype                                                                                                        
                                                                                                                                                                                       
        proc = AssertDtype("test_tensor", dtype="uint8")                                                                                                                               
        tensor = xr.DataArray(np.zeros((1,), dtype="uint8"), dims=tuple("c"))                                                                                                          
        out = proc(tensor)                                                                                                                                                             
        assert out is tensor                                                                                                                                                           
                                                                                                                                                                                       
        tensor = tensor.astype("uint16")                                                                                                                                               
        with pytest.raises(AssertionError):                                                                                                                                            
            out = proc(tensor)                                                                                                                                                         
>           assert out is tensor                                                                                                                                                       
E           Failed: DID NOT RAISE <class 'AssertionError'>                                                                                                                             
                                                                                                                                                                                       
prediction_pipeline/test_processing.py:27: Failed  
```

But let's first see if we get the other tests to run.

**Comment by FynnBe** [comment]
> I get this test failure locally though:

this is really confusing. I just double checked this one locally for me and it passes... looking at it I have no idea how that one could fail... ?!?
hmm... maybe if you somehow have some optimization flags active that skip the assert statement in `AssertDtype`?

**Comment by FynnBe** [comment]
interestingly the error for py3.7 is: `AttributeError: 'str' object has no attribute 'decode'`

**Comment by constantinpape** [comment]
These test errors are very weird... Let's see if they go away tomorrow...

**Comment by FynnBe** [comment]
the CI installed tensorflow 2.4.1 which is older than what was used to create the test model.. (2.9)...

**Comment by constantinpape** [comment]
Awesome, thanks for figuring it out @FynnBe.

**Pull request merged**
