### PR TITLE
use numpy.ufuncs instead of xarray.ufuncs

### PR DESCRIPTION
**Pull request by FynnBe**

### CODE REVIEW

**Comment by FynnBe** [comment]
fixes #281

**Comment by FynnBe** [comment]
not sporadic, but PR unrelated:
```
 Encountered problems while solving:
    - package tensorflow-1.15.0-mkl_py37h28c19af_0 is excluded by strict repo priority

**Comment by Czaki** [comment]
Could you make a new release as `2022.6.0` removed `ufunc` module?

**Comment by constantinpape** [comment]
@FynnBe can you please draft a new release?

**Pull request merged**
