### PR TITLE
Update for resolved paths

### PR DESCRIPTION
**Pull request by FynnBe**
needs https://github.com/bioimage-io/spec-bioimage-io/pull/433

### CODE REVIEW

**Comment by FynnBe** [comment]
This PR also adds a completely new test ("test_no_req_measures_for_mode_fixed") After "fixing" it I was wondering how it ever passed before. when I was going to commit it I realized it was a half-finished test I only had locally... so now we have one more test :-)

**Comment by constantinpape** [comment]
Cool, let's wait till the new spec release is on conda-forge and all tests pass.

**Comment by FynnBe** [comment]
weird exceptions are thrown: (a broken tifffile package???)
```tests/test_prediction.py:78: in _test_predict_with_padding
    imageio.imwrite(in_path, image)
/usr/share/miniconda/envs/bio-core-torch/lib/python3.7/site-packages/imageio/v2.py:238: in imwrite
    with imopen(uri, "wi", **imopen_args) as file:
/usr/share/miniconda/envs/bio-core-torch/lib/python3.7/site-packages/imageio/core/imopen.py:198: in imopen
    candidate_plugin = config.plugin_class
/usr/share/miniconda/envs/bio-core-torch/lib/python3.7/site-packages/imageio/config/plugins.py:100: in plugin_class
    module = importlib.import_module(self.module_name, self.package_name)
/usr/share/miniconda/envs/bio-core-torch/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:677: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:728: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
/usr/share/miniconda/envs/bio-core-torch/lib/python3.7/site-packages/imageio/plugins/tifffile.py:176: in <module>
    import tifffile as _tifffile
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   from .tifffile import __doc__, __all__, __version__, main
E     File "/usr/share/miniconda/envs/bio-core-torch/lib/python3.7/site-packages/tifffile/tifffile.py", line 916
E       /,
E       ^
E   SyntaxError: invalid syntax

/usr/share/miniconda/envs/bio-core-torch/lib/python3.7/site-packages/tifffile/__init__.py:3: SyntaxError
```

**Comment by constantinpape** [comment]
Yea, you need to pin an older tifffile package, I had the same issue in some other packages
https://github.com/mobie/mobie-utils-python/blob/master/environment.yaml#L15

**Pull request merged**
