### PR TITLE
Expose model_adapter for the BioEngine

### PR DESCRIPTION
**Pull request by oeway**

### CODE REVIEW

**Comment by oeway** [comment]
This is to allow passing a custom model adapter. In the BioEngine, we want to use the triton api to run the model inference. This will allow us to keep the pre and post processing in the code but run inference with the triton api.

Yes,this change is suggested by @FynnBe

**Review by constantinpape — APPROVED** [review]
Looks good to me. @FynnBe can you give it another look? This is more in your wheelhouse.

**Comment by oeway** [comment]
> Looks good to me. @FynnBe can you give it another look? This is more in your wheelhouse.

We did this change together over a meeting.

**Comment by constantinpape** [comment]
Ok, I went ahead and merge then. @oeway do you also need a release for this right now?

**Comment by oeway** [comment]
> Ok, I went ahead and merge then. @oeway do you also need a release for this right now?

It's fine to wait for the next release.

**Pull request merged**
