### PR TITLE
Improve test-model

### PR DESCRIPTION
**Pull request by FynnBe**
add comparisons of test inputs/outputs to inputs/outputs shape definitions

### CODE REVIEW

**Comment by FynnBe** [comment]
closes #158

**Comment by FynnBe** [comment]
current error ` _pickle.UnpicklingError: invalid load key, '\x0a'.` for py3.9 looks like a pytorch version mismatch...

"backwards incompatible changes" -- https://github.com/pytorch/pytorch/releases/tag/v1.10.0

**Comment by FynnBe** [comment]
the pytorch limit introduced in e022dde is only due to the older test models we use, not fundamentally conflicting with bioimageio.core (although this is untested so far).

**Comment by constantinpape** [comment]
> the pytorch limit introduced in [e022dde](https://github.com/bioimage-io/core-bioimage-io-python/commit/e022dde36c28210f0e3c5953675f5858cfa3756b) is only due to the older test models we use, not fundamentally conflicting with bioimageio.core (although this is untested so far).

We could instead just exclude the incompatible models from the tests with something like `skipIf(pyver >= 3.9)`.

**Comment by FynnBe** [comment]
> > the pytorch limit introduced in [e022dde](https://github.com/bioimage-io/core-bioimage-io-python/commit/e022dde36c28210f0e3c5953675f5858cfa3756b) is only due to the older test models we use, not fundamentally conflicting with bioimageio.core (although this is untested so far).
> 
> We could instead just exclude the incompatible models from the tests with something like `skipIf(pyver >= 3.9)`.

true, much better solution.
actually I'm not even entirely sure that the pytorh version is the problem .. the actual breaking changes don't mention anything that sounds related... let's see if tests start passing after excluding certain models.

**Comment by constantinpape** [comment]
Hmm the tests still fail, maybe we should pin an older pytorch version for now?

**Comment by FynnBe** [comment]
haven't tested all three pytorch state dict models individually, they are all filtered out now for pytorch >= 3.10. (fingers crossed!) in python 3.7 and 3.8 they are still tested. in the long run we probably add more models anyway or give at least the unet2d broad nuclei an update...

**Comment by FynnBe** [comment]
no idea why tests pass (except for conda-build) for 7600de3, but not for 7be4aba. The former was to debug the latter and only adds logs?!?

**Comment by constantinpape** [comment]
> no idea why tests pass (except for conda-build) for [7600de3](https://github.com/bioimage-io/core-bioimage-io-python/commit/7600de3bc7bc74f0fdeac4b6f3a575abe434c2dc), but not for [7be4aba](https://github.com/bioimage-io/core-bioimage-io-python/commit/7be4aba5fb929b7fdb46934ec3e80b6e409a6f51). The former was to debug the latter and only adds logs?!?

Well, as long as they pass now.... Same conda issue as in https://github.com/bioimage-io/spec-bioimage-io/pull/282.
Maybe the python version was bumped and now leads to these issues?

**Comment by FynnBe** [comment]
no recent python releases (https://www.python.org/downloads/), but yesterday conda 4.11.0 was released: https://docs.conda.io/projects/conda/en/latest/release-notes.html#id1

**Comment by FynnBe** [comment]
noteworthy enhancement: Add `--dry-run` option to `conda env create` (#10635)

**Comment by constantinpape** [comment]
> but yesterday conda 4.11.0 was released:

That sounds like a good candidate...
I suggest we deactvate the conda-build tests for now.

**Comment by FynnBe** [comment]
> I suggest we deactvate the conda-build tests for now.

we can also just ignore them for now...
so... I could just go ahead and merge this PR?

**Comment by constantinpape** [comment]
I went ahead and merged it ;).

**Pull request merged**
